import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { cn } from "@/lib/utils";
import { ModeToggle } from "@/app/theme";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    themeColor: [
        {media: "(prefers-color-scheme: light)", color: "white"},
        {media: "(prefers-color-scheme: dark)", color: "black"},
    ],
    description: "Generated by create next app",
};

export function Navbar() {
    return (
        <>
            <div className="invisible sm:visible relative w-full overflow-hidden md:p-4 lg:p-8">
                <div className="float-left">
                    <ModeToggle/>
                </div>

                <div className="logo-container absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
                    <div>
                        <a className="block dark:hidden" href="/">
                            <Image src="/logo_dark.svg" alt="SnipHub Logo" width={ 256 } height={ 32 }/>
                        </a>
                        <a className="hidden dark:block" href="/">
                            <Image src="/logo_light.svg" alt="SnipHub Logo" width={ 256 } height={ 32 }/>
                        </a>
                    </div>
                </div>
            </div>

        </>
    )
}

export interface BgGridProps {
    children?: React.ReactNode;
}

export function BgGrid({children}: BgGridProps) {
    return (
        <div
            className="absolute inset-0 h-full w-full bg-white dark:bg-slate-950 bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] dark:bg-[radial-gradient(#0f172a_1px,transparent_1px)] [background-size:16px_16px]">
            { children }
        </div>
    )
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <html lang="en" suppressHydrationWarning>
            <head/>
            <body
                className={ cn(
                    "min-h-screen bg-background font-sans antialiased",
                    inter.className)
                }
            >
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                <BgGrid>
                    <Navbar/>
                    <div className="relative min-h-screen">
                        <div className="flex-1">{ children }</div>
                    </div>
                </BgGrid>
            </ThemeProvider>
            </body>
            </html>
        </>
    );
}
